name: Renovate

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 7 * * 1-5"

permissions:
  contents: write
  pull-requests: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      # https://github.com/renovatebot/github-action
      - name: Renovate
        uses: renovatebot/github-action@v44.0.2
        env:
          LOG_LEVEL: info
          RENOVATE_TOKEN: ${{ secrets.GH_TOKEN }}
          RENOVATE_REPOSITORIES: ${{ github.repository }}
        with:
          renovate-version: latest
          configurationFile: .github/renovate.json
